/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActiveIcon: typeof import('./components/global/ActiveIcon.vue')['default']
    DataPoint: typeof import('./components/global/DataPoint.vue')['default']
    DataPoints: typeof import('./components/global/DataPoints.vue')['default']
    DateLog: typeof import('./components/dividends/DateLog.vue')['default']
    DividendsCalendar: typeof import('./components/dividends/DividendsCalendar.vue')['default']
    FiftyTwoWeekDisplay: typeof import('./components/stocks/FiftyTwoWeekDisplay.vue')['default']
    LastDividendCard: typeof import('./components/stocks/LastDividendCard.vue')['default']
    LogList: typeof import('./components/dividends/LogList.vue')['default']
    LogSummary: typeof import('./components/dividends/LogSummary.vue')['default']
    MoverCard: typeof import('./components/markets/MoverCard.vue')['default']
    MoverList: typeof import('./components/markets/MoverList.vue')['default']
    MoverLists: typeof import('./components/markets/MoverLists.vue')['default']
    NavigationDrawer: typeof import('./components/navigation/NavigationDrawer.vue')['default']
    NavigationLinks: typeof import('./components/navigation/NavigationLinks.vue')['default']
    PageHeader: typeof import('./components/global/PageHeader.vue')['default']
    PortfolioSummary: typeof import('./components/stocks/PortfolioSummary.vue')['default']
    PreviousCloseCard: typeof import('./components/stocks/PreviousCloseCard.vue')['default']
    PreviousCloseForm: typeof import('./components/stocks/PreviousCloseForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchForm: typeof import('./components/stocks/SearchForm.vue')['default']
    TopNavigation: typeof import('./components/navigation/TopNavigation.vue')['default']
    UserList: typeof import('./components/users/UserList.vue')['default']
  }
}
