version: '3'
services:
  stocker:
    build: .
    ports:
      - '3010:3010'
    container_name: stocker
    volumes:
      - ./:/app
      - v-stocker:/app/node_modules
    env_file:
      - ./.env
    networks:
      - stocker
volumes:
  v-stocker:
networks:
  stocker:
    external: true
